name: FuminExtends
version: @version@
main: com.github.rnlin.rnlibrary.test.Rlibrary
api-version: 1.15.2

commands:
  setfly:
    description: It's main commands of this plugin.
    aliases: [sf,fl,flymode]
    usage:
      /<command>
    permisson: fuminlib.command.main.fly
    permission-message: You don't have the permission <permission>.
permissions:
  fuminlib.command.main.fly:
     description: mamiyafumin permissions.
     default: true